# Nav
social:
  Github: https://github.com/aaaaaandy

menu:
  Home: /blog
  Category: /blog/category
  Tag: /blog/tag
  About: /blog/about

# Background image, color
background: ''

# Favicon
favicon: img/favicon.ico

# SEO
keywords: 'hexo, andy'

# Widgets, enable at least one
widgets:
  category: enabled
  archive: disable
  tag: enabled

# Set the first image in post to cover
auto_cover: true
